PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZETL_CBR_RULE1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZETL_CBR_RULE1-RULE_ID .
    FIELD ZETL_CBR_RULE1-COMPANY_CODE .
    FIELD ZETL_CBR_RULE1-ACCOUNT .
    FIELD ZETL_CBR_RULE1-GL_PROJ_CODE .
    FIELD ZETL_CBR_RULE1-GL_PROD_CODE .
    FIELD ZETL_CBR_RULE1-SUB_CODE .
    FIELD ZETL_CBR_RULE1-PART_REGION .
    FIELD ZETL_CBR_RULE1-GL_DEPT_CODE .
    FIELD ZETL_CBR_RULE1-PARENT_PART_NO .
    FIELD ZETL_CBR_RULE1-PART_NO .
    FIELD ZETL_CBR_RULE1-CREATED_BY .
    FIELD ZETL_CBR_RULE1-CREATION_DATE .
    FIELD ZETL_CBR_RULE1-LAST_UPDATE_LOGIN .
    FIELD ZETL_CBR_RULE1-LAST_UPDATED_BY .
    FIELD ZETL_CBR_RULE1-LAST_UPDATE_DATE .
    FIELD ZETL_CBR_RULE1-DELIND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZETL_CBR_RULE1-RULE_ID .
    FIELD ZETL_CBR_RULE1-COMPANY_CODE .
    FIELD ZETL_CBR_RULE1-ACCOUNT .
    FIELD ZETL_CBR_RULE1-GL_PROJ_CODE .
    FIELD ZETL_CBR_RULE1-GL_PROD_CODE .
    FIELD ZETL_CBR_RULE1-SUB_CODE .
    FIELD ZETL_CBR_RULE1-PART_REGION .
    FIELD ZETL_CBR_RULE1-GL_DEPT_CODE .
    FIELD ZETL_CBR_RULE1-PARENT_PART_NO .
    FIELD ZETL_CBR_RULE1-PART_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
