PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZETL_CBR_RULE2 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZETL_CBR_RULE2-RULE_ID .
    FIELD ZETL_CBR_RULE2-COMPANY_CODE .
    FIELD ZETL_CBR_RULE2-ACCOUNT .
    FIELD ZETL_CBR_RULE2-PROFIT_CENTER .
    FIELD ZETL_CBR_RULE2-PURPOSE_OF_RULE .
    FIELD ZETL_CBR_RULE2-PASS_COUNTER .
    FIELD ZETL_CBR_RULE2-STATUS .
    FIELD ZETL_CBR_RULE2-RULE_DESCR .
    FIELD ZETL_CBR_RULE2-PRODUCT_HIERARCHY .
    FIELD ZETL_CBR_RULE2-CUSTOMER .
    FIELD ZETL_CBR_RULE2-STATISTIC_AMOUNT .
    FIELD ZETL_CBR_RULE2-JOURNAL_LINE_DESCR .
    FIELD ZETL_CBR_RULE2-EXTERNAL_BILLING_ELEMENT .
    FIELD ZETL_CBR_RULE2-TRADING_PARTNER .
    FIELD ZETL_CBR_RULE2-PARTNER_PROFIT_CENTER .
    FIELD ZETL_CBR_RULE2-CREATED_BY .
    FIELD ZETL_CBR_RULE2-CREATION_DATE .
    FIELD ZETL_CBR_RULE2-LAST_UPDATE_LOGIN .
    FIELD ZETL_CBR_RULE2-LAST_UPDATED_BY .
    FIELD ZETL_CBR_RULE2-LAST_UPDATE_DAT .
    FIELD ZETL_CBR_RULE2-DELIND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZETL_CBR_RULE2-RULE_ID .
    FIELD ZETL_CBR_RULE2-COMPANY_CODE .
    FIELD ZETL_CBR_RULE2-ACCOUNT .
    FIELD ZETL_CBR_RULE2-PROFIT_CENTER .
    FIELD ZETL_CBR_RULE2-PURPOSE_OF_RULE .
    FIELD ZETL_CBR_RULE2-PASS_COUNTER .
    FIELD ZETL_CBR_RULE2-STATUS .
    FIELD ZETL_CBR_RULE2-RULE_DESCR .
    FIELD ZETL_CBR_RULE2-PRODUCT_HIERARCHY .
    FIELD ZETL_CBR_RULE2-CUSTOMER .
    FIELD ZETL_CBR_RULE2-STATISTIC_AMOUNT .
    FIELD ZETL_CBR_RULE2-JOURNAL_LINE_DESCR .
    FIELD ZETL_CBR_RULE2-EXTERNAL_BILLING_ELEMENT .
    FIELD ZETL_CBR_RULE2-TRADING_PARTNER .
    FIELD ZETL_CBR_RULE2-PARTNER_PROFIT_CENTER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
