PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZRAR_ENRICH_ENH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZRAR_ENRICH_ENH-BUKRS .
    FIELD ZRAR_ENRICH_ENH-VBELN .
    FIELD ZRAR_ENRICH_ENH-POSNR .
    FIELD ZRAR_ENRICH_ENH-PSTYV .
    FIELD ZRAR_ENRICH_ENH-BEGDA .
    FIELD ZRAR_ENRICH_ENH-ENDDA .
    FIELD ZRAR_ENRICH_ENH-WRBTR .
    FIELD ZRAR_ENRICH_ENH-WAERS .
    FIELD ZRAR_ENRICH_ENH-DMBTR .
    FIELD ZRAR_ENRICH_ENH-LOC_CURRCY .
    FIELD ZRAR_ENRICH_ENH-DMBE2 .
    FIELD ZRAR_ENRICH_ENH-LC2_CURR .
    FIELD ZRAR_ENRICH_ENH-ERDAT .
    FIELD ZRAR_ENRICH_ENH-AEDAT .
    FIELD ZRAR_ENRICH_ENH-ERNAM .
    FIELD ZRAR_ENRICH_ENH-CHANGEUSER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZRAR_ENRICH_ENH-BUKRS .
    FIELD ZRAR_ENRICH_ENH-VBELN .
    FIELD ZRAR_ENRICH_ENH-POSNR .
    FIELD ZRAR_ENRICH_ENH-PSTYV .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
